[BUGFIX] Ensure only one progress-bar-element is rendered at a time
When changing between modules there are sometimes multiple progress
bar rendered, since the first one was not finished loading.

Detect this race condition now, and reuise the progress-bar-element
as long as it exists.

Note that this lead to strict mode violations in playwright tests:

> Error: strict mode violation: locator('typo3-backend-progress-bar')
> resolved to 2 elements:
> 1) <typo3-backend-progress-bar max="100" value="100">
>    </typo3-backend-progress-bar> aka
>    locator('typo3-backend-progress-bar').filter({ hasText: '100%' })
> 2) <typo3-backend-progress-bar max="100" value="0">
>    </typo3-backend-progress-bar> aka
>    locator('typo3-backend-progress-bar').filter({ hasText: /^0%$/ })

Releases: main
Resolves: #109075
Change-Id: I61be46dabde237fdc6af6bfad4686426a44f4a0c
Reviewed-on: https://review.typo3.org/c/Packages/TYPO3.CMS/+/92965
Tested-by: core-ci <typo3@b13.com>
Tested-by: Benjamin Kott <benjamin.kott@outlook.com>
Reviewed-by: Sven Liebert <mail@sven-liebert.de>
Tested-by: Sven Liebert <mail@sven-liebert.de>
Tested-by: Jochen Roth <rothjochen@gmail.com>
Reviewed-by: Jochen Roth <rothjochen@gmail.com>
Reviewed-by: Benjamin Kott <benjamin.kott@outlook.com>